import { getBlog, saveBlog } from '@/lib/storage';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { Calendar, ArrowLeft, Sparkles, Tag } from 'lucide-react';
import { format } from 'date-fns';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeRaw from 'rehype-raw';

export async function generateMetadata({ params }) {
    const { username, slug } = await params;
    const blog = await getBlog(username, slug);
    if (!blog) return { title: 'Not Found' };
    return { title: `${blog.title} | ${username}'s Blog` };
}

export default async function BlogPostPage({ params }) {
    const { username, slug } = await params;
    const blog = await getBlog(username, slug);

    if (!blog) {
        notFound();
    }

    // Next.js static rendering might clash with writing, so we skip view incrementing for MVP during server render
    // Instead, just read it directly.

    return (
        <div className="min-h-screen py-12 px-4 bg-[#0a0f18]">
            <div className="max-w-3xl mx-auto">
                <Link href={`/blog/${username}`} className="inline-flex items-center gap-2 text-slate-400 hover:text-white transition-colors mb-10 text-sm font-medium">
                    <ArrowLeft size={16} /> Back to {username}'s blog
                </Link>

                <header className="mb-12">
                    <div className="flex items-center gap-3 mb-6">
                        <span className="bg-blue-500/20 text-blue-300 px-3 py-1 rounded-full text-xs font-medium border border-blue-500/20">
                            {blog.category}
                        </span>
                        <span className="text-slate-400 text-sm flex items-center gap-1.5">
                            <Calendar size={14} />
                            {format(new Date(blog.date), 'MMMM d, yyyy')}
                        </span>
                        <span className="text-slate-500 text-sm flex items-center gap-1.5 ml-auto bg-white/5 px-3 py-1 rounded-full border border-white/5">
                            <Sparkles size={14} className="text-violet-400" />
                            Generated by {blog.aiModel}
                        </span>
                    </div>

                    <h1 className="text-4xl md:text-5xl font-extrabold text-white tracking-tight leading-tight mb-6">
                        {blog.title}
                    </h1>

                    {blog.tags && blog.tags.length > 0 && (
                        <div className="flex gap-2 items-center flex-wrap">
                            <Tag size={16} className="text-slate-500" />
                            {blog.tags.map(tag => (
                                <span key={tag} className="text-sm text-slate-400">#{tag}</span>
                            ))}
                        </div>
                    )}
                </header>

                <div className="prose prose-invert prose-lg max-w-none prose-img:rounded-xl prose-img:shadow-2xl prose-a:text-blue-400">
                    <ReactMarkdown
                        remarkPlugins={[remarkGfm]}
                        rehypePlugins={[rehypeRaw]}
                    >
                        {blog.markdown}
                    </ReactMarkdown>
                </div>

                <footer className="mt-20 pt-8 border-t border-white/10 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <div className="w-12 h-12 bg-gradient-to-tr from-blue-500 to-violet-500 rounded-full flex items-center justify-center text-xl font-bold text-white shadow-xl">
                            {username.charAt(0).toUpperCase()}
                        </div>
                        <div>
                            <div className="text-white font-medium">Written by {username}</div>
                            <div className="text-sm text-slate-400">With the help of AI</div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
    );
}
